In [1]:
## Done By: Nayan Man Singh Pradhan

In [3]:
import numpy as np

In [16]:
a = np.array([[1],[1],[0]])
b = np.array([[-1],[2],[5]])
M = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
print('a =\n', a)
print('b =\n', b)
print('M =\n', M)

a =
 [[1]
 [1]
 [0]]
b =
 [[-1]
 [ 2]
 [ 5]]
M =
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
