In [85]:
## Done By: Nayan Man Singh Pradhan

In [86]:
## Programming Exercise 1

In [87]:
## Importing 
import numpy as np
import scipy.linalg as linalg

In [88]:
## Creating vectors/matrices
a = np.array([[1],[1],[0]])
b = np.array([[-1],[2],[5]])
M = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

## Printing to check
print('a =\n', a)
print('b =\n', b)
print('M =\n', M)

a =
 [[1]
 [1]
 [0]]
b =
 [[-1]
 [ 2]
 [ 5]]
M =
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [95]:
## Defining all functions used in this programming exercise

## Function that computes inner product
def inner_product_calc(a, b):
    return np.inner(a,b)

## Function that computes matrix vector product
def matrix_vector_product_calc(M, b):
    return np.dot(M, b)
#     return M@b ## this works too

## Function that computes vector norm
def norm_calc(a):
    return np.linalg.norm(a)

## Function that computes solution of linear system using LU factorization
def LU_solver(M, b):
    LU = linalg.lu_factor(M)
    return (linalg.lu_solve(LU, b))

## Function that computes solution of linear system using Cholesky factorization
def Cholesky_solver(M, b):
    c, low = linalg.cho_factor(M)
    return (linalg.cho_solve((c, low), b))

In [96]:
## a) Compute and print the inner product between a and b
inner_product = inner_product_calc(a, b)
print("Inner Product =\n", inner_product)

Inner Product =
 [[-1  2  5]
 [-1  2  5]
 [ 0  0  0]]


In [97]:
## b) Compute and print the matrix-vector product between M and b
matrix_vector_product = matrix_vector_product_calc(M, b)
print("Matrix Vector Product = \n", matrix_vector_product)

Matrix Vector Product = 
 [[-4]
 [ 0]
 [ 8]]


In [98]:
## c) Compute and print the l2 norm of b
l2_norm = norm_calc(b)
print("Norm of vector \n{}\n==>".format(b), l2_norm)

Norm of vector 
[[-1]
 [ 2]
 [ 5]]
==> 5.477225575051661


In [105]:
## d) Compute and print the solution x of the linear system of equations Mx=b using LU factorization
solution_x_using_LU = LU_solver(M, b)
print("Using LU factorization, \nx = \n", solution_x_using_LU)

Using LU factorization, 
x = 
 [[1.5]
 [4. ]
 [4.5]]


In [106]:
## e) Compute and print the solution x of the linear system of equations Mx=b using the Cholesky factorization
solution_x_using_Cholesky = Cholesky_solver(M, b)
print("Using Cholesky factorization, \nx = \n", solution_x_using_Cholesky)

Using Cholesky factorization, 
x = 
 [[1.5]
 [4. ]
 [4.5]]
