In [18]:
## Done By: Nayan Man Singh Pradhan

In [19]:
## Programming Exercise 1

In [3]:
## Importing numpy
import numpy as np

In [17]:
## Creating vectors/matrices
a = np.array([[1],[1],[0]])
b = np.array([[-1],[2],[5]])
M = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

## Printing to check
print('a =\n', a)
print('b =\n', b)
print('M =\n', M)

a =
 [[1]
 [1]
 [0]]
b =
 [[-1]
 [ 2]
 [ 5]]
M =
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [51]:
## Defining function that computes inner product
def inner_product_calc(a, b):
    return np.inner(a,b)

## Defining function that computes matrix vector product
def matrix_vector_product_calc(M, b):
    return np.dot(M, b)
#     return M@b ## this works too

## Defining function that computes vector norm
def norm_calc(a):
    return np.linalg.norm(a)

In [49]:
## a) Compute and print the inner product between a and b
inner_product = inner_product_calc(a, b)
print("Inner Product =\n", inner_product)

Inner Product =
 [[-1  2  5]
 [-1  2  5]
 [ 0  0  0]]


In [50]:
## b) Compute and print the matrix-vector product between M and b
matrix_vector_product = matrix_vector_product_calc(M, b)
print("Matrix Vector Product = \n", matrix_vector_product)

Matrix Vector Product = 
 [[-4]
 [ 0]
 [ 8]]


In [57]:
## c) Compute and print the l2 norm of b
l2_norm = norm_calc(b)
print("Norm of vector \n{}\n==>".format(b), l2_norm)

Norm of vector 
[[-1]
 [ 2]
 [ 5]]
==> 5.477225575051661
