In [292]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import collections
from numpy.linalg import inv

In [227]:
N = 30

np.random.seed(123)
X1 = np.random.multivariate_normal([1,1],[[1,0],[0,1]],N)
X1 = np.concatenate((X1,1.0*np.ones((N,1))),axis=1)
X2 = np.random.multivariate_normal([-1,-1],[[1,0],[0,1]],N)
X2 = np.concatenate((X2,2.0*np.ones((N,1))),axis=1)
X3 = np.random.multivariate_normal([2,0],[[1,0],[0,1]],N)
X3 = np.concatenate((X3,3.0*np.ones((N,1))),axis=1)

X = np.concatenate((X1,X2,X3));

In [250]:
# print(X)

X = np.array([(1,1,0), (2,3,0), (5,1,1), (5,2,2)])
print(X)

[[1 1 0]
 [2 3 0]
 [5 1 1]
 [5 2 2]]


In [251]:
N_g_list = []

for i in range(len(X)):
    ind = int(X[i][-1])
    N_g_list.append(ind)
    
N_g = collections.Counter(N_g_list)
print(N_g)

Counter({0: 2, 1: 1, 2: 1})


In [252]:
p_g = []

for i in (N_g):
    p_g.append((N_g[i])/len(N_g_list))

print(p_g)

[0.5, 0.25, 0.25]


In [255]:
classes = []

for i in (N_g):
    classes.append(i)

In [259]:
x_y_split = [] 
x_list = [[] for i in range(len(N_g))]

for i in range(len(X)):
    x_y_split.append(np.split(X[i], [-1]))
    
# print(x_y_split)
for j in range(len(X)):
    
    for k in range(len(classes)):
        
        if x_y_split[j][1] == classes[k]:
            x_list[k].append(x_y_split[j][0])
#         print(k)
    
#     print (x_y_split[j][1])
print((x_list))

[[array([1, 1]), array([2, 3])], [array([5, 1])], [array([5, 2])]]


In [268]:
mean_list = []

for counter, value in enumerate(N_g):
    mean = (1/N_g[value]) * (sum(x_list[counter]))
    mean_list.append(mean)
    
print(mean_list)

[array([1.5, 2. ]), array([5., 1.]), array([5., 2.])]


In [285]:
coeff_list = []

# print(x_list[3])

for i in range(len(classes)):
    x_minus_mean = x_list[i] - mean_list[i] 
#     print(x_minus_mean)
    coeff = (1/(len(N_g_list)-len(classes)) * (x_minus_mean) * (x_minus_mean).T)
    coeff_list.append(coeff)
#     print(coeff)
             
print(coeff_list)

[array([[ 0.25, -0.5 ],
       [-0.5 ,  1.  ]]), array([[0., 0.],
       [0., 0.]]), array([[0., 0.],
       [0., 0.]])]


In [307]:
x_list = np.array(x_list)
coeff_list = np.array(coeff_list)
max_g = 0

for counter, g in enumerate(classes):
    temp = np.log(g) + ((x_list).T * inv(coeff_list) * mean_list[counter]) - ((1/2) *  mean_list[counter].T * inv(coeff_list) * mean_list[counter])
    if temp > max_g:
        max_g = temp


(3, 2, 2)
[[[ 0.25 -0.5 ]
  [-0.5   1.  ]]

 [[ 0.    0.  ]
  [ 0.    0.  ]]

 [[ 0.    0.  ]
  [ 0.    0.  ]]]


LinAlgError: Singular matrix