# Assignment Sheet 5
## Done by Nayan Man Singh Pradhan

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy.linalg as linalg
from sklearn import linear_model

In [335]:
## y = mx + c

In [113]:
# ## Covariance
# def get_cov(x, y):
#     mean_x = np.mean(x)
#     mean_y = np.mean(y)
#     covar = 0.0
#     for i in range(len(x)):
#         covar += (x[i] - mean_x) * (y[i] - mean_y)
#     return covar

# ## Variance
# def get_var(a):
#     mean = np.mean(a)
#     return sum([(x - mean)**2 for x in a])

# ## For coefficients m and c
# def get_coeff(data):
#     x = [row[0] for row in data]
#     y = [row[1] for row in data]
# #     print ("x=",x)
# #     print ("y=",y)
#     x_mean, y_mean = np.mean(x), np.mean(y)
# #     print(x_mean)
#     m = get_cov(x, y)/ get_var(x)
#     c = y_mean - m * x_mean
#     return [m, c]

# ## Linear Regression
# def linear_reg(train, test):
# #     output_pred = []
#     m, c = get_coeff(train)
#     print (m, c)
# #     for t in test:
# #         y_pred = m * t[0] + c
# #         output_pred.append(y_pred)
# #     return output_pred
#     return m*test + c

In [114]:
# test_X = ([1,2,4,4])
# test_Y = ([4,6,7,8])

# mean_x = get_mean(test_X)
# mean_y = get_mean(test_Y)

# print(get_var(test_X))

# dataset = [[1, 1], [2, 3], [4, 3], [3, 2], [5, 5]]
# print(linear_reg(dataset))

In [115]:
# X = np.array([[0, 0], [1,2], [2,4], [3,0], [4,1]])
# y = np.array([0, 0.3, 0.75, 1, 2])

# ziped = list(zip(X,y))

# # coef = get_coeff(ziped)
# # print(coef)

# # test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2,2))
# # test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2, 2))
# test = np.array([[0,4]])

# predictor = linear_reg(ziped, test)

# print(predictor)

[ 0.44976077 -0.00600858] [0.0454067  0.82021459]
[[0.0454067  0.79618026]]


In [284]:
# fig = plt.figure(figsize=(6, 5))
# ax = Axes3D(fig, elev=45, azim=-120)
# ax.scatter(X[:, 0], X[:, 1], y, c='r', marker='o', label='training set')
# # ax.plot_surface(np.array([[-1, -1], [5, 5]]), np.array([[-1, 5], [-1, 5]]), lin_regr.predict(np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2, 2)), alpha=.5, label='linear regression predictor')
# # ax.plot_surface(X[:, 0], X[:, 1], predictor)
# ax.set_xlabel('input X_1')
# ax.set_ylabel('input X_2')
# ax.set_zlabel('output Y')
# plt.title("Simplistic test of linear regression on 2d input")
# plt.show()




#     ## z
#     temp_1 = np.ones((1,1))
#     z = np.vstack((temp_1, B_hat))
#     print("z=", z)
    
#     ## y_pred <-- zT B_hat
#     print(z.T.shape)
#     print(B_hat.shape)
    
#     y_pred = np.dot(z.T, B_hat)
#     print(y_pred)

In [63]:
def Cholesky_solver(M, b):
    c, low = linalg.cho_factor(M)
    return (linalg.cho_solve((c, low), b))

def lin_reg(train, test):
    x = [i[0] for i in train]
    y = [i[1] for i in train]
    
    ## Build matrix X
    x = np.array(x)
    y = np.array(y)
    
    x_of1 = np.ones((x.shape[0], 1))
#     print(x_of1)
#     print(x)
    X = np.hstack((x_of1, x))
#     print("X=", X)
    
    ## b <-- X.T y
    b = np.dot(X.T, y)

#     print("b=", b)
    
    ## A <-- X.T X
    A = np.dot(X.T, X)
#     print("A=", A)
    
    ## Solve AB = b using Cholesky factorization
    B_hat = Cholesky_solver(A, b)
#     B_hat = B_hat[np.newaxis, :].T
#     print("B_hat=", B_hat)
    
    return B_hat

In [64]:
## Example 4.1
print("Example 4.1\n")
X = np.array([[1,0],[1,1],[2,1],[4,2]])
y = np.array([1,2,4,5])

train = list(zip(X, y))
test = np.array([[0,4]])

## Predict using self implemented function
predictor_function = lin_reg(train, test)
print("Result from self implementation:")
print("Intercept: ", predictor_function[0])
print("Coefficient: ", predictor_function[1:])

print("-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-")

## Library to check
lin_reg_library = linear_model.LinearRegression()
lin_reg_library.fit(X, y)
lib_pred = lin_reg_library.predict(test)
print("Result from library:")
print("Intercept: ", lin_reg_library.intercept_)
print("Coefficient: ", lin_reg_library.coef_)

Example 4.1

Result from self implementation:
Intercept:  0.6666666666666665
Coefficient:  [0.66666667 1.        ]
-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-
Result from library:
Intercept:  0.6666666666666674
Coefficient:  [0.66666667 1.        ]


In [66]:
## Example 4.2
print("Example 4.1\n")
X = [[0], [1], [2], [3], [4]]
y = [0, 0.3, 0.75, 1, 2]

train = list(zip(X, y))
test = np.array([3])

## Predict using self implemented function
predictor_function = lin_reg(train, test)
print("Result from self implementation:")
print("Intercept: ", predictor_function[0])
print("Coefficient: ", predictor_function[1:])

print("-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-")

## Library to check
lin_reg_library = linear_model.LinearRegression()
lin_reg_library.fit(X, y)
lib_pred = lin_reg_library.predict(test)
print("Result from library:")
print("Intercept: ", lin_reg_library.intercept_)
print("Coefficient: ", lin_reg_library.coef_)

Example 4.1

Result from self implementation:
Intercept:  -0.1300000000000005
Coefficient:  [0.47]
-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-


ValueError: Expected 2D array, got 1D array instead:
array=[3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [61]:


X = np.array([[0, 0], [1,2], [2,4], [3,0], [4,1]])
y = np.array([0, 0.3, 0.75, 1, 2])

train = list(zip(X, y))
test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T)

## Predict using self implemented function
predictor_function = lin_reg(train, test)
print("Result from self implementation:")
print("Intercept: ", predictor_function[0])
print("Coefficient: ", predictor_function[1:])

print("-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-")

## Library to check
lin_reg_library = linear_model.LinearRegression()
lin_reg_library.fit(X, y)
lib_pred = lin_reg_library.predict(test)
print("Result from library:")
print("Intercept: ", lin_reg_library.intercept_)
print("Coefficient: ", lin_reg_library.coef_)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0 0]
 [1 2]
 [2 4]
 [3 0]
 [4 1]]
Result from self implementation:
Intercept:  -0.12125000000000065
Coefficient:  [ 0.47    -0.00625]
-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-
Result from library:
Intercept:  -0.12125000000000008
Coefficient:  [ 0.47    -0.00625]


In [14]:
def get_function_of_line(a):
    length = len(a)
    fn = ""
    for i in range(0, len(a)):
        if (i==len(a)-1):
            fn = fn + str(a[i]) + "X_" + str(i)
        else:
            fn = fn + str(a[i]) + "X_" + str(i) + ' + '
    return (fn)

tes = np.array([1, 2, 4])
get_function_of_line(tes)

'1X_0 + 2X_1 + 4X_2'