# Assignment Sheet 5
## Done by Nayan Man Singh Pradhan

In [371]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy.linalg as linalg
from sklearn import linear_model

In [335]:
## y = mx + c

In [113]:
# ## Covariance
# def get_cov(x, y):
#     mean_x = np.mean(x)
#     mean_y = np.mean(y)
#     covar = 0.0
#     for i in range(len(x)):
#         covar += (x[i] - mean_x) * (y[i] - mean_y)
#     return covar

# ## Variance
# def get_var(a):
#     mean = np.mean(a)
#     return sum([(x - mean)**2 for x in a])

# ## For coefficients m and c
# def get_coeff(data):
#     x = [row[0] for row in data]
#     y = [row[1] for row in data]
# #     print ("x=",x)
# #     print ("y=",y)
#     x_mean, y_mean = np.mean(x), np.mean(y)
# #     print(x_mean)
#     m = get_cov(x, y)/ get_var(x)
#     c = y_mean - m * x_mean
#     return [m, c]

# ## Linear Regression
# def linear_reg(train, test):
# #     output_pred = []
#     m, c = get_coeff(train)
#     print (m, c)
# #     for t in test:
# #         y_pred = m * t[0] + c
# #         output_pred.append(y_pred)
# #     return output_pred
#     return m*test + c

In [114]:
# test_X = ([1,2,4,4])
# test_Y = ([4,6,7,8])

# mean_x = get_mean(test_X)
# mean_y = get_mean(test_Y)

# print(get_var(test_X))

# dataset = [[1, 1], [2, 3], [4, 3], [3, 2], [5, 5]]
# print(linear_reg(dataset))

In [115]:
# X = np.array([[0, 0], [1,2], [2,4], [3,0], [4,1]])
# y = np.array([0, 0.3, 0.75, 1, 2])

# ziped = list(zip(X,y))

# # coef = get_coeff(ziped)
# # print(coef)

# # test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2,2))
# # test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2, 2))
# test = np.array([[0,4]])

# predictor = linear_reg(ziped, test)

# print(predictor)

[ 0.44976077 -0.00600858] [0.0454067  0.82021459]
[[0.0454067  0.79618026]]


In [284]:
# fig = plt.figure(figsize=(6, 5))
# ax = Axes3D(fig, elev=45, azim=-120)
# ax.scatter(X[:, 0], X[:, 1], y, c='r', marker='o', label='training set')
# # ax.plot_surface(np.array([[-1, -1], [5, 5]]), np.array([[-1, 5], [-1, 5]]), lin_regr.predict(np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T).reshape((2, 2)), alpha=.5, label='linear regression predictor')
# # ax.plot_surface(X[:, 0], X[:, 1], predictor)
# ax.set_xlabel('input X_1')
# ax.set_ylabel('input X_2')
# ax.set_zlabel('output Y')
# plt.title("Simplistic test of linear regression on 2d input")
# plt.show()




#     ## z
#     temp_1 = np.ones((1,1))
#     z = np.vstack((temp_1, B_hat))
#     print("z=", z)
    
#     ## y_pred <-- zT B_hat
#     print(z.T.shape)
#     print(B_hat.shape)
    
#     y_pred = np.dot(z.T, B_hat)
#     print(y_pred)

In [375]:
def Cholesky_solver(M, b):
    c, low = linalg.cho_factor(M)
    return (linalg.cho_solve((c, low), b))

def lin_reg(train, test):
    x = [i[0] for i in train]
    y = [i[1] for i in train]
    
    ## Build matrix X
    x = np.array(x)
    y = np.array(y)
    
    x_of1 = np.ones((x.shape[0], 1))
    print(x_of1)
    print(x)
    X = np.hstack((x_of1, x))
#     print("X=", X)
    
    ## b <-- X.T y
    b = np.dot(X.T, y)

#     print("b=", b)
    
    ## A <-- X.T X
    A = np.dot(X.T, X)
#     print("A=", A)
    
    ## Solve AB = b using Cholesky factorization
    B_hat = Cholesky_solver(A, b)
#     B_hat = B_hat[np.newaxis, :].T
#     print("B_hat=", B_hat)
    
    return B_hat

In [350]:
## Example 4.1
X = np.array([[1,0],[1,1],[2,1],[4,2]])
y = np.array([1,2,4,5])

train = list(zip(X, y))
test = np.array([[0,4]])

predictor_function = lin_reg(train, test)
print("Prediction of coefficients by self implementation:", predictor_function)


## Library to check
lin_reg_library = linear_model.LinearRegression()
lin_reg_library.fit(X, y)
lib_pred = lin_reg_library.predict(test)
print('Prediction of coefficients by library:',lin_reg_library.intercept_, lin_reg_library.coef_)

[[1.]
 [1.]
 [1.]
 [1.]]
[[1 0]
 [1 1]
 [2 1]
 [4 2]]
Prediction of coefficients by self implementation: [0.66666667 0.66666667 1.        ]
Prediction of coefficients by library: 0.6666666666666674 [0.66666667 1.        ]


In [352]:
## Example 4.2

X = np.array([0,1,2,3,4])
y = np.array([0,0.3,0.75,1,2])

train = list(zip(X, y))
test = np.array([3])

lin_reg_predictor = lin_reg(train, test) 
print(lin_reg_predictor)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[0 1 2 3 4]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [353]:
X = np.array([[0, 0], [1,2], [2,4], [3,0], [4,1]])
y = np.array([0, 0.3, 0.75, 1, 2])

train = list(zip(X, y))
test = (np.array([[-1, -1, 5, 5], [-1, 5, -1, 5]]).T)

predictor_function = lin_reg(train, test)
print("Prediction of coefficients by self implementation:", predictor_function)

## Library to check
lin_reg_library = linear_model.LinearRegression()
lin_reg_library.fit(X, y)
lib_pred = lin_reg_library.predict(test)
print('Prediction of coefficients by library:',lin_reg_library.intercept_, lin_reg_library.coef_)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0 0]
 [1 2]
 [2 4]
 [3 0]
 [4 1]]
Prediction of coefficients by self implementation: [-0.12125  0.47    -0.00625]
Prediction of coefficients by library: -0.12125000000000008 [ 0.47    -0.00625]


In [378]:
tes = np.array([1, 2, 4])
get_function_of_line(tes)

def get_function_of_line(vec):
    length = len(vec)
    print(length)
    fn = ""
    for i in range(0, len(vec)):
        print(vec[i])
#         fn = fn + str(vec[i]) + "x^" + str(i)
    print(fn)

3


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')